name: lint, test and deploy worfkflow
on: push
jobs:
  lintTest:
    runs-on: ubuntu-latest
    steps:
      - name: lint the code
        run: npm run lint
      - name: test the code
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: lintTest
    steps:
      - name: deploy code
        run: echo 'deploying..'