name: lint, test and deploy worfkflow
on: push
jobs:
  preSetup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        uses: npm ci
  lintTest:
    runs-on: ubuntu-latest
    needs: preSetup
    steps:
      - name: lint the code
        run: npm run lint
      - name: test the code
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: lintTest
    steps:
      - name: deploy code
        run: echo 'deploying..'